apiVersion: v1
kind: Service
metadata:
    name: teomapipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: teomapipelinesjavascriptdocker
